version: '3'
services:
  database: 
    build: 
        context: ./docker/mariadb
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PSW}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mariadb/data:/var/lib/mysql
    restart: on-failure
  app:
    build:
        context: .
        dockerfile: docker/php/Dockerfile
    volumes:
      - './app/${PROJECT_DIR}/:/usr/src/app'
    user: '${LOCAL_USER}:${LOCAL_USER}'
    privileged: true
  nginx: 
    image: nginx:1.23.0-alpine
    restart: on-failure
    volumes:
      - './app/${PROJECT_DIR}/public/:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '${NGINX_PORT}:80'
    depends_on:
      - app
  